---
name: CI Build
on:
  schedule:
    - cron: '28 0 * * 1'
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  TF_IN_AUTOMATION: true

jobs:
  static-checks:
    name: "Static-checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Setup Terraaform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28
      - name: "Run pre-commit checks"
        uses: pre-commit/action@v2.0.0

  image:
    name: "Build docker image"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: "Setup Google SDK (push)"
        if: github.event_name == 'push'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '307.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build image (pull_request)
        if: github.event_name == 'pull_request'
        run: ./build.sh
        env:
          IMAGE_TAG: ${{ github.sha }}
          PROJECT_ID: github-action

      - name: Build and publish image (push)
        if: github.event_name == 'push'
        run: |
          gcloud auth configure-docker
          ./build.sh
          ./push.sh
        env:
          IMAGE_TAG: ${{ github.sha }}

  deploy:
    name: "Terraform (push)"
    needs: [static-checks, image]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: "Setup Google SDK"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '307.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: "Setup Terraaform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: ../log_stream.sh plan terraform plan -no-color
        env:
          TF_VAR_github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        working-directory: terraform

      - name: Terraform Apply (push)
        if: github.event_name == 'push'
        run: |
          ../log_stream.sh apply terraform apply -auto-approve
          echo "Terraform outputs:"
          terraform output
        working-directory: terraform
        env:
          TF_VAR_docker_image_tag: ${{ github.sha }}
          TF_VAR_github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
